-- Active: 1709542531305@@127.0.0.1@1521@orcl@SYSTEM
--HR 계정 생성
-- c## 접두어 없이도 계정 생성
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
-- 계정 ID, PW 생성
CREATE USER dog IDENTIFIED BY 123456;
-- 테이블 스테이스 지정
ALTER USER dog DEFAULT TABLESPACE users;
-- 용량 설정
ALTER USER dog QUOTA UNLIMITED ON users;
-- 권한 부여
GRANT DBA TO dog;



CREATE TABLE lent (
    lent_num    number      not null,
	user_num	NUMBER		NOT NULL,
	isbn	    VARCHAR2(100)		NOT NULL,
    status      varchar2(50) NOT NULL,
	lent_date	Date DEFAULT sysdate NOT NULL,
	late_date	Date DEFAULT sysdate NOT NULL,
	plus_date	Date DEFAULT sysdate NOT NULL
);


  CREATE TABLE "DOG"."BOOK" 
   (	"BNAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ISBN" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"AUTHOR" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MAKE_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"TOTAL" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


  CREATE TABLE "DOG"."USERS" 
   (	"ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"BIRTH" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"JOIN_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"PHONE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"USER_NUM" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

